In [10]:
import numpy as np

def matrix_operations(matrix1, matrix2):
    addition = matrix1 + matrix2
    subtraction = matrix1 - matrix2
    transpose_M1 = np.transpose(matrix1)
    transpose_M2 = np.transpose(matrix2)
    product = matrix1 * matrix2
    dot_product = np.dot(matrix1, matrix2)
    
    return {
        'addition': addition,
        'subtraction': subtraction,
        'transpose1': transpose_M1,
        'transpose2': transpose_M2,
        'element_wise_product': product,
        'dot_product': dot_product
    }


matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

result = matrix_operations(matrix_a, matrix_b)

print("Addition:\n", result['addition'])
print("Subtraction:\n", result['subtraction'])
print("Transpose of Matrix 1:\n", result['transpose1'])
print("Transpose of Matrix 2:\n", result['transpose2'])
print("Element-wise Product:\n", result['element_wise_product'])
print("Dot Product:\n", result['dot_product'])


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Transpose of Matrix 1:
 [[1 3]
 [2 4]]
Transpose of Matrix 2:
 [[5 7]
 [6 8]]
Element-wise Product:
 [[ 5 12]
 [21 32]]
Dot Product:
 [[19 22]
 [43 50]]
